# Copyright 2018, Google, Inc.
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
    - name: 'gcr.io/${PROJECT_ID}/terraform'
      dir: terraform/
      args: ['init',
        '-backend-config=project=${PROJECT_ID}',
        '-backend-config=bucket=${_BUCKET}']
      env:
        - "TF_VAR_project_id=${_PROJECT}"
    
    - name: 'gcr.io/${PROJECT_ID}/terraform'
      dir: terraform/
      args: ['plan', '-out=./plan.out']
      env:
        - "TF_VAR_project_id=${_PROJECT}"
    
    - name: gcr.io/${PROJECT_ID}/terraform-validator
      dir: terraform/
      args: ['convert', './plan.out', '--project={$PROJECT_ID}']
    
    - name: gcr.io/cloud-builders/gcloud
      args: ['source', 'repos', 'clone', 'policy-library']
    
    - name: gcr.io/${PROJECT_ID}/terraform-validator
      args: ['validate', 'terraform/plan.out', '--policy-path=./policy-library/', '--project={$PROJECT_ID}']
    
    - name: 'gcr.io/${PROJECT_ID}/terraform'
      dir: terraform/
      args: ['apply', '-auto-approve', './plan.out']
      env:
        - "TF_VAR_project-name=${_PROJECT}"
    
    substitutions:
        _BUCKET: # Terraform state bucket name
        _PROJECT: # Project to provision resources